import { createElement } from '@lwc/engine-dom';
import RelatedRelationshipContactsList from 'c/relatedRelationshipContactsList';

describe('c-related-relationship-contacts-list', () => {
    afterEach(() => {
        
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        
        const element = createElement('c-related-relationship-contacts-list', {
            is: RelatedRelationshipContactsList
        });

        
        document.body.appendChild(element);

    
        expect(1).toBe(1);
    });
});